### ISSUE TITLE
[DEPRECATED] warning message during tests

### ISSUE THREAD

**Issue by laarchambault** [learn-co-curriculum/ruby-building-applications-gems-and-bundler#2]
When running tests on this file, we receive the following messages. It appears the test files call a method that will no longer be supported soon. The message appears for bundler_spec.rb: 6, bundler_spec.rb 56, and as below, bunder)spec.rb 68:

[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /Users/lauraarchambault/Development/code/ruby-building-applications-gems-and-bundler-atlanta-web-021720/spec/bundler_spec.rb:68)

[DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'test'`, and stop using this flag

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
